[package]
name = "mh_map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
base64 = "0.21.0"
image = "0.24.5"
imageproc = "0.23.0"
jpeg-encoder = "0.5.1"
zune-jpeg = "0.2.0"
